# ========================================
# Server Configuration
# ========================================
server.port=${PORT:8080}
# ========================================
# MySQL Database Configuration
# ========================================
# ========================================
# TiDB Cloud Database Configuration
# ========================================

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/media_app?sslMode=VERIFY_IDENTITY

spring.datasource.username=3WsNJiE4Vt21csB.root

spring.datasource.password=hB01iDsc62DGXPwz

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========================================
# JPA / Hibernate
# ========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true


# ========================================
# Cloud Storage Configuration
# ========================================
storage.type=cloudinary

cloudinary1.cloud-name=cvb8gitg
cloudinary1.api-key=714132452944662
cloudinary1.api-secret=pxmQPvy3NCMyJZWJ8U8FINcJnfU

cloudinary2.cloud-name=dxwooovry
cloudinary2.api-key=547338678399287
cloudinary2.api-secret=9gVjHYYjdAsIHdpGN-kLuyEpNPw
# ========================================
# JWT Configuration
# ========================================
application.security.jwt.secret-key=bXlfc3VwZXJfc2VjcmV0X2tleV9mb3JfbWVkaWFfYXBwXzIwMjRfYWJjZGVmZzEyMzQ1Ng==
application.security.jwt.expiration=86400000

# ========================================
# CORS Configuration
# ========================================
app.cors.allowed-origins=https://media-app-front-smoky.vercel.app
